### ISSUE TITLE
can not run sh scripts/train_msrcnn.sh

### ISSUE THREAD

**Issue by JunjieChen-2020** [zju3dv/disprcnn#21]
i finished run build_and_install.
produced a file '_C.cpython-37m-x86_64-linux-gnu.so'
but start sh   scripts/train_msrcnn.sh  make mistakes.
Is it a path problem?

File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/__init__.py", line 9, in <module>
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/nms.py", line 3, in <module>
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/data/datasets/kitti_roi_dataset.py", line 9, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/nms.py", line 3, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn.structures.disparity import DisparityMap
    from disprcnn import _C
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/structures/disparity.py", line 9, in <module>
    from disprcnn import _C
ImportError: cannot import name '_C'
ImportError: cannot import name '_C'
    from disprcnn import _C
ImportError: cannot import name '_C'
    from disprcnn.layers import interpolate
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/tools/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn import _C
ImportError: cannot import name '_C'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/kitti/pob/mask.yaml']' returned non-zero exit status 1.

**Comment by f-sky** [comment]
I guess you are trying to train with the wrong python interpreter.
I strongly recommend you to use anaconda to set up the environment.

**Comment by JunjieChen-2020** [comment]
File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/__init__.py", line 9, in <module>

  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
            from disprcnn.structures.disparity import DisparityMapfrom disprcnn import _Cfrom .nms import nms


ImportError  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
:   File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/structures/disparity.py", line 9, in <module>
/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
    from disprcnn import _C
ImportError    : /home/cjj/testcnn/disprcnn/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSsfrom disprcnn.layers import interpolate

  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn import _C
ImportError: /home/cjj/testcnn/disprcnn/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
Traceback (most recent call last):
  File "tools/train_net.py", line 6, in <module>
    from disprcnn.data import make_data_loader
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/build.py", line 9, in <module>
    from . import datasets as D
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/datasets/__init__.py", line 2, in <module>
    from .kitti_roi_dataset import KITTIRoiDataset
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/datasets/kitti_roi_dataset.py", line 9, in <module>
    from disprcnn.structures.disparity import DisparityMap
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/structures/disparity.py", line 9, in <module>
    from disprcnn.layers import interpolate
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn import _C
ImportError: /home/cjj/testcnn/disprcnn/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
Traceback (most recent call last):
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/disprcnn/bin/python3', '-u', 'tools/train_net.py', '--local_rank=3', '--config-file', 'configs/kitti/pob/mask.yaml']' returned non-zero exit status 1.
(disprcnn) [root@localhost disprcnn]# 


i used  the anaconda emvironment from environment.yaml

**Comment by f-sky** [comment]
You have to re-run "sh build_and_install.sh" if you install a different version of pytorch.

**Comment by JunjieChen-2020** [comment]
i re -run 'sh build_and_install,sh',still report error as follow:
Traceback (most recent call last):
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/disprcnn/bin/python', '-u', 'tools/train_net.py', '--local_rank=3', '--config-file', 'configs/kitti/pob/mask.yaml']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools/train_net.py", line 6, in <module>
    from disprcnn.data import make_data_loader
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/build.py", line 9, in <module>
    from . import datasets as D
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/datasets/__init__.py", line 2, in <module>
    from .kitti_roi_dataset import KITTIRoiDataset
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/data/datasets/kitti_roi_dataset.py", line 9, in <module>
    from disprcnn.structures.disparity import DisparityMap
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/structures/disparity.py", line 9, in <module>
    from disprcnn.layers import interpolate
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/home/cjj/testcnn/disprcnn/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn import _C
ImportError: /home/cjj/testcnn/disprcnn/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by JunjieChen-2020** [comment]
I re-run environment.yaml,and sh build_and_install.the console report the error info as follow:
RuntimeError: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by JunjieChen-2020** [comment]
i can not find the file pointnet2_cuda :'import pointnet2_cuda as pointnet2'.

**Comment by f-sky** [comment]
Run the commands in "build_and_install.sh" line by line, and check which of them report errors.
Update your GPU driver as suggested.

**Comment by f-sky** [comment]
Closed since no updates for a long time. Re-open it if you have any questions.
