### ISSUE TITLE
Could you provide detailed fastai version?

### ISSUE THREAD

**Issue by pengweiweiwei** [zju3dv/disprcnn#27]
While installing fastai dependency,  I meet belowing error:

`ImportError: cannot import name 'SaveModelCallback' from 'fastai.callbacks' (/home/yhzn/anaconda3/envs/disprcnn/lib/python3.7/site-packages/fastai/callbacks/__init__.py)
`
I tried several versions across fastai 1.0.x to 2.0.x,  seemed the belowing three module cant import simulateously. 
`from fastai.basic_train import LearnerCallback, Learner
from fastai.callbacks import SaveModelCallback
from fastai.torch_core import rank_distrib`

I  believe it will be solved if you can provide the detailed fastai version

Looking forward to your reply
Have a nice day!

**Comment by pengweiweiwei** [comment]
@JiamingSuen

**Comment by f-sky** [comment]
Try to use fastai==1.0.62

**Comment by pengweiweiwei** [comment]
Now the problem of fastai is solved,but I meet a mew problem 
`Traceback (most recent call last):
  File "tools/test_net.py", line 9, in <module>
    from disprcnn.modeling.detector import build_detection_model
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/detectors.py", line 3, in <module>
    from .disprcnn import DispRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/disprcnn.py", line 12, in <module>
    from disprcnn.modeling.pointnet_module.point_rcnn.lib.net.point_rcnn import PointRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/__init__.py", line 1, in <module>
    from .point_rcnn.lib.net.point_rcnn import PointRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/net/point_rcnn.py", line 14, in <module>
    from .rcnn_net import RCNNNet
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/net/rcnn_net.py", line 6, in <module>
    from ..pointnet2_lib.pointnet2.pointnet2_modules import PointnetSAModule
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/pointnet2_lib/pointnet2/pointnet2_modules.py", line 5, in <module>
    from . import pointnet2_utils
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/pointnet2_lib/pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/yhzn/anaconda3/envs/disprcnn/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
Traceback (most recent call last):
  File "tools/test_net.py", line 9, in <module>
    from disprcnn.modeling.detector import build_detection_model
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/__init__.py", line 2, in <module>
    from .detectors import build_detection_model
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/detectors.py", line 3, in <module>
    from .disprcnn import DispRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/detector/disprcnn.py", line 12, in <module>
    from disprcnn.modeling.pointnet_module.point_rcnn.lib.net.point_rcnn import PointRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/__init__.py", line 1, in <module>
    from .point_rcnn.lib.net.point_rcnn import PointRCNN
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/net/point_rcnn.py", line 14, in <module>
    from .rcnn_net import RCNNNet
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/net/rcnn_net.py", line 6, in <module>
    from ..pointnet2_lib.pointnet2.pointnet2_modules import PointnetSAModule
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/pointnet2_lib/pointnet2/pointnet2_modules.py", line 5, in <module>
    from . import pointnet2_utils
  File "/home/yhzn/pengwei/disprcnn/disprcnn/modeling/pointnet_module/point_rcnn/lib/pointnet2_lib/pointnet2/pointnet2_utils.py", line 7, in <module>
    import pointnet2_cuda as pointnet2
ImportError: /home/yhzn/anaconda3/envs/disprcnn/lib/python3.7/site-packages/pointnet2-0.0.0-py3.7-linux-x86_64.egg/pointnet2_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
` 
I don't know what happened! Could you give me some advice?
Thanks!

**Comment by pengweiweiwei** [comment]
@f-sky

**Comment by f-sky** [comment]
The building step does not succeed. Try to run [commands](https://github.com/zju3dv/disprcnn/blob/master/build_and_install.sh) line-by-line, and find if there is any error reported.

**Comment by pengweiweiwei** [comment]
when i run sh build_and_install.sh ,the error mentioned aboved occured . But when i run commands line-by-line, the error disappeared. It‘s so strange and i really don't know why . I feel curious. But now the problems is solved . Thanks!

**Comment by f-sky** [comment]
Issue closed. Feel free to re-open it if you have more questions.
