### ISSUE TITLE
请问一下在centos系统上可以跑吗

### ISSUE THREAD

**Issue by loeweli** [zju3dv/disprcnn#41]
我的系统是
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core
训练时报了以下错误：
Traceback (most recent call last):
  File "tools/train_net.py", line 6, in <module>
    from disprcnn.data import make_data_loader
  File "/data/llw/disprcnn/disprcnn/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/data/llw/disprcnn/disprcnn/data/build.py", line 9, in <module>
    from . import datasets as D
  File "/data/llw/disprcnn/disprcnn/data/datasets/__init__.py", line 2, in <module>
    from .kitti_roi_dataset import KITTIRoiDataset
  File "/data/llw/disprcnn/disprcnn/data/datasets/kitti_roi_dataset.py", line 11, in <module>
    from disprcnn.layers import interpolate
  File "/data/llw/disprcnn/disprcnn/layers/__init__.py", line 9, in <module>
    from .nms import nms
  File "/data/llw/disprcnn/disprcnn/layers/nms.py", line 3, in <module>
    from disprcnn import _C
ImportError: /data/llw/disprcnn/disprcnn/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
和系统会有关系吗？

**Comment by f-sky** [comment]
当然可以。应该是你build_and_install.sh报错了。你一行行运行里面的命令，看看什么地方报错。

**Comment by loeweli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by loeweli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
