### ISSUE TITLE
您好，请教一下在centos7下遇到的问题

### ISSUE THREAD

**Issue by zyiqin** [zju3dv/disprcnn#49]
2023-02-12 12:35:57,821 disprcnn.utils.checkpoint INFO: Loading checkpoint from models/kitti/car/pob/mask/smrcnn.pth
2023-02-12 12:36:01,779 disprcnn.inference INFO: Start evaluation on kitti_val_pob_car dataset(3769 images).
  0%|                                                                    | 0/3769 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/public/zyq/anaconda3/envs/tf1.14/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/zyq/anaconda3/envs/tf1.14/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/zyq/anaconda3/envs/tf1.14/lib/python3.7/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/public/zyq/anaconda3/envs/tf1.14/lib/python3.7/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/public/zyq/anaconda3/envs/tf1.14/bin/python', '-u', 'tools/test_net.py', '--local_rank=0', '--config-file', 'configs/kitti/car/pob/mask.yaml', '--ckpt', 'models/kitti/car/pob/mask/smrcnn.pth', 'DATASETS.TEST', "('kitti_val_pob_car',)"]' died with <Signals.SIGSEGV: 11>.

从Ubuntu迁移到centos遇到的问题，build没有问题，请问有什么办法吗？

**Comment by ootts** [comment]
看起来你是用多卡进行的distributed inference,你可以用单卡跑，然后再看看是否有报错么？

**Comment by zyiqin** [comment]
单卡也是同样的报错

**Comment by ootts** [comment]
看看CPU内存是不是溢出

**Comment by zyiqin** [comment]
没有溢出，请问还有什么别的原因吗？

**Comment by ootts** [comment]
开debug，单步前进，看能否找到稳定崩溃的地方
